"""US2: resume error-path integration tests for metadata and rebinding.

These tests correspond to T026 in ``tasks.md`` and exercise negative
paths for the runtime's resume semantics, focusing on FR-009 and
SC-002 edge cases:

1. Missing swarm metadata when starting in resume mode.
2. Mismatched Agent Mail project identifier for dev-mode fake client.
3. Mismatched per-agent Agent Mail identity.
4. Mismatched per-agent ACP conversation identifier.
5. Incomplete or legacy metadata (with empty identity/conversation
   fields) still resumes successfully.

They complement the happy-path resume test in
``tests/integration/quickstart/test_resume_swarm_us2.py`` by locking
in failure behavior while the resume logic is small and easy to reason
about.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pytest

from nate_ntm.config.runtime_config import RuntimeConfig, load_runtime_config
from nate_ntm.runtime.daemon import (
    MetadataMissingError,
    RuntimeDaemon,
    RuntimeStartupError,
)
from nate_ntm.runtime.metadata_store import AgentMetadata, MetadataStore, SwarmMetadata
from nate_ntm.runtime.state import RuntimeStatus


def _make_project(tmp_path: Path) -> Path:
    project = tmp_path / "project"
    project.mkdir(parents=True, exist_ok=True)
    return project


def _base_swarm(config: RuntimeConfig) -> SwarmMetadata:
    """Construct a minimal SwarmMetadata instance for tests.

    By default this uses a simple placeholder Agent Mail project ID
    (``"mail-project-1"``) so that existing US1-style metadata remains
    valid. Tests that need strict fake-client rebinding semantics
    override ``agent_mail_project_id`` explicitly.
    """

    now = datetime(2026, 7, 3, 12, 0, 0)
    return SwarmMetadata(
        swarm_id=config.swarm_id,
        project_path=config.project_path,
        agent_mail_project_id="mail-project-1",
        created_at=now,
        last_updated_at=now,
        agents={},
    )


def test_resume_errors_when_swarm_metadata_missing(tmp_path: Path) -> None:
    """T026.1: mode=resume fails fast when swarm metadata is missing.

    Expectation: :class:`MetadataMissingError` is raised before any
    attempt to construct a :class:`RuntimeDaemon` when ``swarm.json``
    does not exist for the project.
    """

    project = _make_project(tmp_path)
    config: RuntimeConfig = load_runtime_config(project_path=project)

    with pytest.raises(MetadataMissingError):
        RuntimeDaemon.resume(config)


def test_resume_fails_on_fake_agent_mail_project_id_mismatch(tmp_path: Path) -> None:
    """T026.2: FakeAgentMailClient project mismatch triggers RuntimeStartupError.

    This test simulates the case where ``swarm.json`` contains a
    ``agent_mail_project_id`` generated by :meth:`RuntimeDaemon.create`
    (``"fake-mail-project:..."``), but the dev-mode fake client would
    derive a different project identifier for the same config. On
    resume this must be treated as a hard error.
    """

    project = _make_project(tmp_path)
    config: RuntimeConfig = load_runtime_config(project_path=project)
    store = MetadataStore(config=config)

    swarm = _base_swarm(config)
    # Override with a plausible fake-client-style value that will *not*
    # match the one derived from this config by FakeAgentMailClient.
    swarm = SwarmMetadata(
        swarm_id=swarm.swarm_id,
        project_path=swarm.project_path,
        agent_mail_project_id="fake-mail-project:some-other-project",
        created_at=swarm.created_at,
        last_updated_at=swarm.last_updated_at,
        agents=swarm.agents,
        runtime_options=swarm.runtime_options,
    )

    store.save_swarm_metadata(swarm)

    with pytest.raises(RuntimeStartupError) as excinfo:
        daemon = RuntimeDaemon.resume(config)
        # ``daemon`` should never be constructed successfully, but keep
        # the assignment here for clarity about intent.
        _ = daemon

    assert "Agent Mail project ID mismatch on resume" in str(excinfo.value)


def test_resume_fails_on_agent_mail_identity_mismatch(tmp_path: Path) -> None:
    """T026.3: Agent Mail identity mismatch for an agent fails resume.

    The runtime treats divergence between the adapter-derived
    ``agent_mail_identity`` and the value stored in
    :class:`AgentMetadata` as a startup error to protect FR-009.
    """

    project = _make_project(tmp_path)
    config: RuntimeConfig = load_runtime_config(project_path=project)
    store = MetadataStore(config=config)

    now = datetime(2026, 7, 3, 12, 0, 0)

    agent = AgentMetadata(
        agent_id="nav-1",
        display_name="Navigator 1",
        agent_mail_identity="some-other-identity",
        conversation_id="",  # not relevant for this test
    )

    swarm = SwarmMetadata(
        swarm_id=config.swarm_id,
        project_path=config.project_path,
        agent_mail_project_id="mail-project-1",
        created_at=now,
        last_updated_at=now,
        agents={agent.agent_id: agent},
    )

    store.save_swarm_metadata(swarm)
    store.save_agent_metadata(agent)

    with pytest.raises(RuntimeStartupError) as excinfo:
        RuntimeDaemon.resume(config)

    assert "Agent Mail identity mismatch on resume" in str(excinfo.value)


def test_resume_fails_on_conversation_id_mismatch(tmp_path: Path) -> None:
    """T026.4: ACP conversation_id mismatch for an agent fails resume.

    Similar to the Agent Mail identity case, divergence between the
    adapter-derived conversation identifier and the value stored in
    :class:`AgentMetadata` is treated as a startup error.
    """

    project = _make_project(tmp_path)
    config: RuntimeConfig = load_runtime_config(project_path=project)
    store = MetadataStore(config=config)

    now = datetime(2026, 7, 3, 12, 0, 0)

    agent = AgentMetadata(
        agent_id="nav-1",
        display_name="Navigator 1",
        agent_mail_identity="",  # not relevant for this test
        conversation_id="some-other-conversation",
    )

    swarm = SwarmMetadata(
        swarm_id=config.swarm_id,
        project_path=config.project_path,
        agent_mail_project_id="mail-project-1",
        created_at=now,
        last_updated_at=now,
        agents={agent.agent_id: agent},
    )

    store.save_swarm_metadata(swarm)
    store.save_agent_metadata(agent)

    with pytest.raises(RuntimeStartupError) as excinfo:
        RuntimeDaemon.resume(config)

    assert "ACP conversation ID mismatch on resume" in str(excinfo.value)


def test_resume_allows_incomplete_legacy_metadata_with_empty_fields(tmp_path: Path) -> None:
    """T026.5: Empty identity/conversation fields do not block legacy resumes.

    For older or hand-crafted metadata that does not yet include
    identity and conversation identifiers, the runtime should still be
    able to start in ``resume`` mode. Empty strings are treated as
    "no binding present" and are therefore exempt from strict
    FR-009 rebinding checks.
    """

    project = _make_project(tmp_path)
    config: RuntimeConfig = load_runtime_config(project_path=project)
    store = MetadataStore(config=config)

    now = datetime(2026, 7, 3, 12, 0, 0)

    agent = AgentMetadata(
        agent_id="nav-1",
        display_name="Navigator 1",
        agent_mail_identity="",  # no identity persisted yet
        conversation_id="",  # no conversation persisted yet
    )

    swarm = SwarmMetadata(
        swarm_id=config.swarm_id,
        project_path=config.project_path,
        agent_mail_project_id="mail-project-1",
        created_at=now,
        last_updated_at=now,
        agents={agent.agent_id: agent},
    )

    store.save_swarm_metadata(swarm)
    store.save_agent_metadata(agent)

    daemon = RuntimeDaemon.resume(config)
    daemon.start()

    assert daemon.state.status is RuntimeStatus.RUNNING
    assert daemon.swarm_metadata.swarm_id == config.swarm_id
    assert set(daemon.swarm_metadata.agents.keys()) == {"nav-1"}
